# Configure this Discovery Server

eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself (unless running
           # multiple discovery servers for redundancy)
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 9090  # HTTP (Tomcat) port

zuul:
 routes:
       products1:
        path : /api/service1/**
        url : http://localhost:9091/    
       products2:
        path : /api/service2/**
        url : http://localhost:9092/test
        
  
  